### ISSUE TITLE
Running 'djanto-admin print-version' does not work

### ISSUE THREAD

**Issue by biofsphere** [DCOD-OpenSource/django-project-version#21]
# Running 'django-admin print-version' does not work. 

## Expected Behavior
When running django-admin print-version I was hoping to get my project's version as per last git commit.

## Current Behavior
django-admin does not acknowledge 'print-version' command.

## Possible Solution
If such a command is indeed available, perhaps improving usage instructions might help newcomers.

## Steps to Reproduce
After pip install django-project-version and adding 'djversion' to django settings INSTALLED_APPS variable, run django-admin print-version.

**Comment by biofsphere** [comment]
In fact, running python manage.py print-version worked just fine.

**Comment by vint21h** [comment]
Hello,
please ensure the "DJANGO_SETTINGS_MODULE" environment variable is set and points to your settings module.

**Comment by vint21h** [comment]
Nobody cares - closed.
