### ISSUE TITLE
Doesn't support Django v5

### ISSUE THREAD

**Issue by pcraig3** [DCOD-OpenSource/django-project-version#22]
# Issue Summary

Hello! Thank you for the library. Very simple to use and I'm very happy with it.

However, I have a pretty simple Django app and just now I actually found that `django-project-version` is blocking me from upgrading to the next version of Django.

I'm on Django version `4.2.9`, and I tried to update to the latest, which at time of writing is [`5.0.1`](https://docs.djangoproject.com/en/5.0/releases/).

However, I wasn't able to update the package, here's the error I got:

```
Because django-project-version (0.18.1) depends on django (>=3.2,<4.3)
 and no versions of django-project-version match >0.18.1,<0.19.0, django-project-version (>=0.18.1,<0.19.0) requires django (>=3.2,<4.3).
So, because bloom-nofos depends on both django (^5.0.1) and django-project-version (^0.18.1), version solving failed.
```

Not super urgent, but I will need to update my Django version eventually.

## Expected Behavior

`django-project-version` should work with Django 5.

## Current Behavior

See above ☝️ 

## Possible Solution

Probably something like this: https://github.com/DCOD-OpenSource/django-project-version/commit/ac07be53c9f6ac7745ab223e3ad70715e36134e1

## Steps to Reproduce

Start a brand new django project in poetry and then try to add `django-project-version`

**Comment by vint21h** [comment]
Hello,
yep, because I am trying to survive under russian missiles attack and I don't have time to support this project, also, this account (company) owner was killed by russians 1 year and 3 days ago.
But, give me a few days, and will fix it.

**Comment by pcraig3** [comment]
Shit dude, that sounds super difficult, I'm sorry to hear that. We support you here in Canada, I hope the situation improves this year.

No worries on my end, take as long as you need to update the library.

**Comment by vint21h** [comment]
New release with requested support - available.
Due to:
- https://docs.python.org/3/whatsnew/3.12.html
- https://github.com/python/cpython/issues/95299
- https://peps.python.org/pep-0632/
Python 3.12 is not supported, IDK how to maintain this type of installation without pyproject.toml which is not supported by the lot of tools I use, sorry.
