### ISSUE TITLE
Django 4

### ISSUE THREAD

**Issue by AnonBit** [DCOD-OpenSource/django-project-version#5]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
django-project-version 0.16.0 requires django<4.0,>=2.2, but you have django 4.0.3 which is incompatible.

Update to support Django 4.0 ?

**Comment by vint21h** [comment]
Yes, but later, because it is not in high priority for me when I am in the bomb shelter hiding from russian bombardments.

**Comment by AnonBit** [comment]
oh ok

**Comment by Archmonger** [comment]
@vint21h Best wishes to you and your family ❤

**Comment by smjaberl** [comment]
@vint21h Best wishes to you and your family, too.  Maybe you have some time to update the dependencies...

**Comment by vint21h** [comment]
https://pypi.org/project/django-project-version/0.17.0/
